### ISSUE TITLE
Install on Raspberry Pi

### ISSUE THREAD

**Issue by endrehp** [ngrok/ngrok-javascript#120]
Hi everyone,

I'm trying to install @ngrok/ngrok (version 1.0.0) on a raspberry pi (Linux ARM release: 4.19.97-v7l+).
And I'm getting this error when I try to require the package in node:
```bash
Welcome to Node.js v16.17.0.
Type ".help" for more information.
> require('@ngrok/ngrok')
Uncaught:
Error: /home/pi/ngrok-test/node_modules/@ngrok/ngrok-linux-arm-gnueabihf/ngrok.linux-arm-gnueabihf.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'ERR_DLOPEN_FAILED'
}
```

I've tried checking dependencies, verifying permissions, and reinstalling ngrok.
Any guidance on how to troubleshoot and resolve this issue?

**Comment by endrehp** [comment]
Thank you!

I have a Raspberry Pi 4 Model B Rev 1.1 with 2GB ram and Linux ARM release: 4.19.97-v7l+.
I managed to build the binary locally, and it works. Thanks for the suggestion!
I guess there's a compatibility issue with the ngrok.linux-arm-gnueabihf.node file in the repo for my rpi version?

**Comment by bobzilladev** [comment]
Hi here, I was not able to load a raspios [2020-05-28](https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2020-05-28/) with `4.19.118-v7+` on the 4, errors on boot due to the software being too old. This [2021-12-02](https://downloads.raspberrypi.com/raspios_oldstable_lite_armhf/images/raspios_oldstable_lite_armhf-2021-12-02/) with `5.10.63-v7+` runs ngrok-javascript without issue.

I'm happy that compiling it locally is working since that's probably the way forward here, but out of curiosity, what distribution are you running with the older `4.19.97-v7l+` kernel?

**Comment by endrehp** [comment]
I'm running Raspbian GNU/Linux 10 (buster).
This solution works fine for me. Thanks again!

**Comment by bobzilladev** [comment]
Glad that solution is working for you! I'll close the issue, let us know if you run into anything else. Thanks!
