### ISSUE TITLE
GenericFailure - tls handshake error

### ISSUE THREAD

**Issue by deejaybill** [ngrok/ngrok-javascript#137]
Hi, 

I've got this error recently with the @ngrok/ngrok@1.2.0 with Node.js 21.7.3 

```
Node.js web server at 8080 is running...
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: failed to connect session: tls handshake error] {
  code: 'GenericFailure'
}

Node.js v21.7.3
```

Even with the quick start sample that you can find on this page, is enough to get the same error:
https://dashboard.ngrok.com/get-started/setup/nodejs

I'm using the authorization token and as a fallback, I've switched back to the Windows agent that works fine.

**Comment by bobzilladev** [comment]
Hello, thanks for writing in! Can you tell us more about your environment (type of machine, operating system and kernel version, etc)? Are you running the linked example code exactly?

When this has happened before it has been an issue with system libraries on the device, a workaround for which is compiling ngrok-javascript on the device itself rather than using the pre-compiled published versions. If you are comfortable trying that, it requires a working rust compiler and node setup, after which `yarn install` then `yarn build` should bake a binary optimized for the local environment.

Looking forward to hearing back!

**Comment by bobzilladev** [comment]
Nothing looks amiss with the code here. I was able to run it on both `Windows 11 Home 23H2` and `Windows Server 2022 Datacenter 21H2` machines.

The generic TLS handshake error is likely an issue with the pre-built code not working well with the crypto libraries on the local machine. In cases like that building the SDK locally will usually solve the issue, if you want to attempt going that route. Since the golang agent is working it's unlikely to be a network issue. Another possibility is trying to run the python SDK, but that is built on the same github runner machines and may run into the same error.

**Comment by bobzilladev** [comment]
We'll go ahead and close this ticket out, feel free to reopen if you need help with a local build, or if any more information becomes available. Thanks for writing in!
